#' Convert polynomial objects from Momocs into expressions
#'
#' Convert polynomial objects from Momocs into expressions
#' that can be evaluated by e.g. \code{stats::deriv3()}.
#'
#' @param poly An OpnCoe object generated by \code{Momocs::npoly()} or \code{Momocs::opoly()}.
#' @return an expression.
#' @examples
#' x <- 1:10
#' y <- x^2
#'
#' #a fictional landmark dataset
#' mdat <- matrix(c(x,y), nrow=10, ncol=2)
#'
#' my_poly <- Momocs::npoly(mdat, 2)
#'
#' express(my_poly)
#'
#' @seealso \code{\link{param}} for t-parameterizing Momocs polynomials
#' and \code{\link{func}} for creating R functions.


# express()

# credit to user: \033$BM{E/8;\033(B at:
# https://stackoverflow.com/questions/40438195/function-for-polynomials-of-arbitrary-order-symbolic-method-preferred

express <- function(poly, expr = TRUE) {
    coeffs <- poly[[1]]  #extract coefficients from npoly list
    stringexpr <- paste("x", seq_along(coeffs) - 1, sep = " ^ ")
    stringexpr <- paste(stringexpr, coeffs, sep = " * ")
    stringexpr <- paste(stringexpr, collapse = " + ")
    if (expr)
        return(parse(text = stringexpr)) else return(stringexpr)

}


#' Parameterize polynomial objects from Momocs
#'
#' Convert polynomial objects from Momocs into t-parameterized
#' polynomials readable by \code{pracma::arclength()}.
#'
#' @param poly An OpnCoe object generated by \code{Momocs::npoly()} or \code{Momocs::opoly()}.
#' @return a polynomial (e.g. y=x^2) function of the form
#' \code{function(t) {t, t^2}}.
#' @examples
#' x <- 1:10
#' y <- x^2
#'
#' #a fictional landmark dataset
#' mdat <- matrix(c(x,y), nrow=10, ncol=2)
#'
#' my_poly <- Momocs::npoly(mdat, 2)
#'
#' param(my_poly)
#'
#' @seealso \code{\link{express}} for converting Momocs polynomials to expressions
#' and \code{\link{func}} for creating R functions.

# param()

# how to create a fuction programatically
# https://stackoverflow.com/questions/12982528/how-to-create-an-r-function-programmatically
# https://stackoverflow.com/questions/9345373/as-alist-character



param <- function(poly, expr = TRUE) {
    coeffs <- poly[[1]]  #extract coefficients from npoly list
    stringchar <- paste("x", seq_along(coeffs) - 1, sep = " ^ ")
    stringchar <- paste(stringchar, coeffs, sep = " * ")
    stringchar <- paste(stringchar, collapse = " + ")
    paramchar <- paste("x", stringchar, sep = " , ")
    bodychar <- paste0("c(", paramchar, ")")  #add 'c()'

    bodyexp <- eval(parse(text = paste("alist(", bodychar, ")")))

    f <- function(x) NULL
    body(f) <- bodyexp[[1]]
    f
}



#' Convert polynomial objects from Momocs into a function
#'
#' Convert polynomial objects from Momocs into a function
#'  readable by ...
#'
#' @param poly An OpnCoe object generated by \code{Momocs::npoly()} or \code{Momocs::opoly()}.
#' @return a polynomial function (e.g. y = x^2) of the form \code{function(x) {x^2}}.
#' @examples
#' x <- 1:10
#' y <- x^2
#'
#' #a fictional landmark dataset
#' mdat <- matrix(c(x,y), nrow=10, ncol=2)
#'
#' my_poly <- Momocs::npoly(mdat, 2)
#'
#' func(my_poly)
#' @seealso \code{\link{express}} for converting Momocs polynomials to expressions
#' and \code{\link{param}} for parameterizing by t.

# func()

func <- function(poly, expr = TRUE) {
    coeffs <- poly[[1]]  #extract coefficients from npoly list
    stringexpr <- paste("x", seq_along(coeffs) - 1, sep = " ^ ")
    stringexpr <- paste(stringexpr, coeffs, sep = " * ")
    stringexpr <- paste(stringexpr, collapse = " + ")

    bodyexp <- eval(parse(text = paste("alist(", stringexpr, ")")))  #function body
    args <- alist(x = )  #variable names

    f <- as.function(c(args, bodyexp), env = parent.frame())
    f
}


