#' Convert polynomial objects from Momocs into expressions
#'
#' Convert polynomial objects from Momocs into expressions
#' for computing derivatives in R e.g. \code{stats::deriv3()}.
#'
#' @param poly An OpnCoe object generated by \code{Momocs::npoly()} or \code{Momocs::opoly()}.
#'
#' @param expr Indicate whether you want a string or expression returned. Default is expression.
#' @return an expression.
#' @examples
#'
#' library(Momocs)
#'
#' x <- 1:10
#' y <- x^2
#'
#' #a fictional landmark dataset
#' mdat <- matrix(c(x,y), nrow=10, ncol=2)
#'
#' my_poly <- Momocs::npoly(mdat, 2)
#'
#' express(my_poly)
#'
#' @seealso \code{\link{param}} for t-parameterizing Momocs polynomials
#' and \code{\link{func}} for creating R functions.
#'
#' @export


# express()

# credit to user: \033$BM{E/8;\033(B at:
# https://stackoverflow.com/questions/40438195/function-for-polynomials-of-arbitrary-order-symbolic-method-preferred

express <- function(poly, expr = TRUE) {

    #extract coefficients from npoly list
    coeffs <- poly[[1]]
    stringexpr <- paste("x", seq_along(coeffs) - 1,
                        sep = " ^ ")
    stringexpr <- paste(stringexpr, coeffs, sep = " * ")
    stringexpr <- paste(stringexpr, collapse = " + ")
    if (expr)
        return(parse(text = stringexpr)) else return(stringexpr)

}


#' Parameterize polynomial objects from Momocs
#'
#' Convert polynomial objects from Momocs into t-parameterized
#' polynomials readable by \code{pracma::arclength()}.
#'
#' @param poly An OpnCoe object generated by \code{Momocs::npoly()} or \code{Momocs::opoly()}.
#' @return a polynomial (e.g. y=x^2) function of the form
#' \code{function(t) {t, t^2}}.
#' @examples
#'
#' library(Momocs)
#'
#' x <- 1:10
#' y <- x^2
#'
#' #a fictional landmark dataset
#' mdat <- matrix(c(x,y), nrow=10, ncol=2)
#'
#' my_poly <- Momocs::npoly(mdat, 2)
#'
#' param(my_poly)
#'
#' @seealso \code{\link{express}} for converting Momocs polynomials to expressions
#' and \code{\link{func}} for creating R functions.
#'
#' @export

# param()

# how to create a fuction programatically
# https://stackoverflow.com/questions/12982528/how-to-create-an-r-function-programmatically
# https://stackoverflow.com/questions/9345373/as-alist-character



param <- function(poly) {

    #extract coefficients from npoly list
    coeffs <- poly[[1]]
    stringchar <- paste("x", seq_along(coeffs) - 1,
                        sep = " ^ ")
    stringchar <- paste(stringchar, coeffs, sep = " * ")
    stringchar <- paste(stringchar, collapse = " + ")
    paramchar <- paste("x", stringchar, sep = " , ")
    bodychar <- paste0("c(", paramchar, ")")  #add 'c()'

    bodyexp <- eval(parse(text = paste("alist(", bodychar,
                                       ")")))

    f <- function(x) NULL
    body(f) <- bodyexp[[1]]
    f
}



#' Convert polynomial objects from Momocs into a function
#'
#' Convert polynomial objects from Momocs into a function
#'  readable by ...
#'
#' @param poly An OpnCoe object generated by \code{Momocs::npoly()} or \code{Momocs::opoly()}.
#' @return a polynomial function (e.g. y = x^2) of the form \code{function(x) {x^2}}.
#' @examples
#'
#' library(Momocs)
#'
#' x <- 1:10
#' y <- x^2
#'
#' #a fictional landmark dataset
#' mdat <- matrix(c(x,y), nrow=10, ncol=2)
#'
#' my_poly <- Momocs::npoly(mdat, 2)
#'
#'@examples
#'
#' #solve for y values for arc-length parameterized curve
#'
#' library(Momocs)
#'
#' x <- 1:10
#' y <- x^2
#'
#' # a fictional landmark dataset
#' mdat <- matrix(c(x,y), nrow=10, ncol=2)
#'
#' my_poly <- Momocs::npoly(mdat, 2)
#'
#' param_poly <- param(my_poly)
#'
#' subdiv <- 100 # number of times to subdivide the curve
#' iter <- seq(0, 1, by=1/subdiv)
#' arcfun_list<- list() # empty bin
#'
#' # arc length of t-parameterized function between x = [0, 1]
#' x_range <- c(0,1)
#' b <- pracma::arclength(param_poly, x_range[1], x_range[2])$length
#'
#' # for every fraction of arclength, b*i, create a function(u) with an unknown
#' # x-coordinate, u. Solve for u by uniroot().
#' for(i in seq_along(iter)){
#'    arcfun_list[[i]] <-
#'        local({
#'            b_sub<-iter[i]*b
#'            function(u) pracma::arclength(param_poly, x_range[1], u)$length - b_sub
#'        })
#'}

#' #root-finding function
#' root_find <- function(x) uniroot(x, x_range)$root

#' # parameterize polynomial function by arc length
#' x <- sapply(arcfun_list, root_find)
#'
#' # solve for corresponding y-values
#' func_poly <- func(my_poly)
#'
#' y <- func_poly(x)
#'
#' @seealso \code{\link{express}} for converting Momocs polynomials to expressions
#'
#'
#' @export

# func()

func <- function(poly) {

    #extract coefficients from npoly list
    coeffs <- poly[[1]]
    stringexpr <- paste("x", seq_along(coeffs) - 1,
                        sep = " ^ ")
    stringexpr <- paste(stringexpr, coeffs, sep = " * ")
    stringexpr <- paste(stringexpr, collapse = " + ")

    bodyexp <- eval(parse(text = paste("alist(", stringexpr,
                                       ")")))  #function body
    args <- alist(x = )  #variable names

    f <- as.function(c(args, bodyexp), env = parent.frame())
    f
}


